## Comparative tabulation of Manidae 
### (aggregated and grouped from web download)

In [10]:
import numpy as np
import pandas as pd
pd.options.mode.chained_assignment = None  # default='warn'

In [2]:
df = pd.read_csv('./downloaded/comptab_2019-05-31 12_46_comma_separated.csv')
df.head()

,Year,App.,Taxon,Class,Order,Family,Genus,Importer,Exporter,Origin,Importer reported quantity,Exporter reported quantity,Term,Unit,Purpose,Source
0,1977,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,FR,GB,XX,NaN,4.0,skins,NaN,NaN,NaN
1,1977,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,US,ES,XX,215.0,NaN,shoes,NaN,NaN,NaN
2,1977,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,US,FR,ID,NaN,444.0,skins,NaN,NaN,NaN
3,1977,II,Manis pentadactyla,Mammalia,Pholidota,Manidae,Manis,AU,CN,NaN,2.0,NaN,live,NaN,NaN,NaN
4,1978,II,Manis crassicaudata,Mammalia,Pholidota,Manidae,Manis,US,JP,XX,298.0,NaN,skins,NaN,NaN,NaN

#### quantiy match between importer's and exporter's reports

In [3]:
df_quantity_comparable = df[df['Importer reported quantity'].notnull() & df['Exporter reported quantity'].notnull()]
df_quantity_comparable_match = df_quantity_comparable[df_quantity_comparable['Importer reported quantity'] == df_quantity_comparable['Exporter reported quantity']]
df_quantity_comparable_match.head()

,Year,App.,Taxon,Class,Order,Family,Genus,Importer,Exporter,Origin,Importer reported quantity,Exporter reported quantity,Term,Unit,Purpose,Source
166,1982,II,Manis pentadactyla,Mammalia,Pholidota,Manidae,Manis,JP,US,ID,2.0,2.0,shoes,NaN,T,NaN
349,1984,II,Manis pentadactyla,Mammalia,Pholidota,Manidae,Manis,US,JP,TH,992.0,992.0,skins,NaN,T,NaN
465,1986,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,US,JP,PH,777.0,777.0,skins,NaN,T,NaN
488,1986,II,Manis pentadactyla,Mammalia,Pholidota,Manidae,Manis,JP,US,XX,2.0,2.0,leather items,NaN,T,NaN
505,1987,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,CH,IT,TH,26.0,26.0,shoes,NaN,NaN,NaN

#### quantity conflict between importer's and exporter's reports

In [18]:
df_quantity_comparable_conflict = df_quantity_comparable[df_quantity_comparable['Importer reported quantity'] != df_quantity_comparable['Exporter reported quantity']]
df_quantity_comparable_conflict['gap percentage'] = ((df_quantity_comparable_conflict['Importer reported quantity'] - df_quantity_comparable_conflict['Exporter reported quantity'])/df_quantity_comparable_conflict['Importer reported quantity']*100).round(1)
df_quantity_comparable_conflict['gap percentage abs'] = df_quantity_comparable_conflict['gap percentage'].abs()

print('              import - export / import')
df_quantity_comparable_conflict.sort_values(by='gap percentage abs', ascending=False)

              import - export / import

,Year,App.,Taxon,Class,Order,Family,Genus,Importer,Exporter,Origin,Importer reported quantity,Exporter reported quantity,Term,Unit,Purpose,Source,gap percentage,gap percentage abs
151,1982,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,US,JP,XX,163.0,7408.0,skins,NaN,T,NaN,-4444.8,4444.8
314,1984,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,US,JP,XX,2.0,75.0,leather products (small),NaN,T,NaN,-3650.0,3650.0
108,1981,II,Manis pentadactyla,Mammalia,Pholidota,Manidae,Manis,US,JP,NaN,663.0,8367.0,skins,NaN,T,NaN,-1162.0,1162.0
877,1996,II,Manis tricuspis,Mammalia,Pholidota,Manidae,Manis,US,TG,NaN,1.0,10.0,live,NaN,T,W,-900.0,900.0
398,1985,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,US,JP,TH,648.0,4940.0,skin pieces,NaN,T,NaN,-662.3,662.3
315,1984,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,US,JP,XX,756.0,4632.0,skins,NaN,T,NaN,-512.7,512.7
1099,2002,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,CN,JP,MY,3.0,16.0,leather products (small),NaN,T,W,-433.3,433.3
86,1981,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,US,JP,NaN,1623.0,8325.0,skins,NaN,T,NaN,-412.9,412.9
1077,2001,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,MX,JP,MY,750.0,2500.0,skins,NaN,T,W,-233.3,233.3
1052,2000,II,Manis pentadactyla,Mammalia,Pholidota,Manidae,Manis,SG,VN,NaN,153.0,500.0,skins,NaN,T,W,-226.8,226.8
586,1989,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,CA,US,TH,1.0,3.0,shoes,NaN,T,NaN,-200.0,200.0
346,1984,II,Manis pentadactyla,Mammalia,Pholidota,Manidae,Manis,US,JP,ID,5.0,14.0,shoes,NaN,T,NaN,-180.0,180.0
420,1985,II,Manis pentadactyla,Mammalia,Pholidota,Manidae,Manis,US,JP,TH,400.0,1002.0,skins,NaN,T,NaN,-150.5,150.5
236,1983,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,US,JP,XX,1440.0,3569.0,skins,NaN,T,NaN,-147.8,147.8
435,1986,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,CH,IT,TH,6.0,14.0,shoes,NaN,NaN,NaN,-133.3,133.3
347,1984,II,Manis pentadactyla,Mammalia,Pholidota,Manidae,Manis,US,JP,ID,200.0,420.0,skins,NaN,T,NaN,-110.0,110.0
544,1987,II,Manis pentadactyla,Mammalia,Pholidota,Manidae,Manis,US,CN,NaN,2.0,4.0,live,NaN,Z,NaN,-100.0,100.0
1226,2008,II,Manis tricuspis,Mammalia,Pholidota,Manidae,Manis,IT,TG,NaN,500.0,5.0,live,NaN,T,R,99.0,99.0
1369,2012,II,Manis temminckii,Mammalia,Pholidota,Manidae,Manis,US,ZA,NaN,8.0,1.0,specimens,NaN,S,W,87.5,87.5
1042,2000,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,US,MX,LA,925.0,1707.0,leather products (small),NaN,T,W,-84.5,84.5
812,1995,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,MX,US,LA,35.0,63.0,skin pieces,kg,T,W,-80.0,80.0
560,1988,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,JP,SG,LA,4600.0,1000.0,skins,NaN,T,NaN,78.3,78.3
858,1996,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,MX,US,LA,999.0,240.0,skins,NaN,T,W,76.0,76.0
1552,2016,II,Manis gigantea,Mammalia,Pholidota,Manidae,Manis,CN,UG,NaN,4000.0,1000.0,scales,kg,T,W,75.0,75.0
1034,2000,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,SG,MY,NaN,21520.0,5610.0,skins,NaN,T,W,73.9,73.9
860,1996,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,SG,MY,NaN,5500.0,9430.0,scales,kg,T,W,-71.5,71.5
557,1988,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,JP,HK,TH,14.0,5.0,skins,NaN,T,NaN,64.3,64.3
513,1987,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,JP,SG,XX,2300.0,850.0,skins,NaN,T,NaN,63.0,63.0
68,1981,II,Manis crassicaudata,Mammalia,Pholidota,Manidae,Manis,US,JP,NaN,556.0,884.0,skins,NaN,T,NaN,-59.0,59.0
493,1986,II,Manis pentadactyla,Mammalia,Pholidota,Manidae,Manis,US,JP,TH,720.0,300.0,skins,NaN,T,NaN,58.3,58.3
1185,2007,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,US,VN,NaN,750.0,1150.0,specimens,ml,S,W,-53.3,53.3
487,1986,II,Manis pentadactyla,Mammalia,Pholidota,Manidae,Manis,JP,US,ID,4.0,2.0,shoes,NaN,T,NaN,50.0,50.0
1544,2016,II,Manis spp.,Mammalia,Pholidota,Manidae,Manis,SN,US,XX,2.0,1.0,skin pieces,NaN,L,I,50.0,50.0
1411,2013,II,Manis tricuspis,Mammalia,Pholidota,Manidae,Manis,HK,TG,NaN,60.0,30.0,scales,kg,T,W,50.0,50.0
780,1994,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,MX,US,LA,1100.0,602.0,skins,NaN,T,W,45.3,45.3
1536,2015,II,Manis tricuspis,Mammalia,Pholidota,Manidae,Manis,US,TG,NaN,17.0,22.0,live,NaN,T,W,-29.4,29.4
1101,2002,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,MX,JP,MY,3542.0,2542.0,skins,NaN,T,W,28.2,28.2
393,1985,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,US,JP,PH,407.0,300.0,skins,NaN,T,NaN,26.3,26.3
890,1997,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,MX,US,LA,2600.0,2100.0,skins,NaN,T,W,19.2,19.2
989,1999,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,SG,MY,NaN,15405.0,12685.0,skins,NaN,T,W,17.7,17.7
466,1986,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,US,JP,TH,8950.0,10477.0,skins,NaN,T,NaN,-17.1,17.1
397,1985,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,US,JP,TH,8845.0,7550.0,skins,NaN,T,NaN,14.6,14.6
312,1984,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,US,JP,TH,757.0,865.0,skins,NaN,T,NaN,-14.3,14.3
222,1983,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,US,IT,SG,15.0,17.0,shoes,NaN,T,NaN,-13.3,13.3
987,1999,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,MX,SG,MY,1700.0,1919.0,skins,NaN,T,W,-12.9,12.9
530,1987,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,US,JP,TH,3626.0,3166.0,skins,NaN,T,NaN,12.7,12.7
1032,2000,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,MX,SG,MY,9987.0,10987.0,skins,NaN,T,W,-10.0,10.0
1029,2000,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,MX,JP,MY,2100.0,2260.0,skins,NaN,T,W,-7.6,7.6
1446,2014,II,Manis gigantea,Mammalia,Pholidota,Manidae,Manis,US,MX,TG,66.0,70.0,leather products (small),NaN,T,W,-6.1,6.1
1035,2000,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,US,JP,MY,4136.0,4322.0,skins,NaN,T,W,-4.5,4.5
810,1995,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,MX,US,LA,225.0,215.0,skins,NaN,T,W,4.4,4.4
223,1983,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,US,IT,TH,27.0,28.0,shoes,NaN,T,NaN,-3.7,3.7
1113,2003,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,MX,JP,MY,1540.0,1500.0,skins,NaN,T,W,2.6,2.6
981,1999,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,JP,SG,MY,5632.0,5537.0,skins,NaN,T,W,1.7,1.7
1033,2000,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,SG,JP,MY,3419.0,3459.0,skins,NaN,T,W,-1.2,1.2
1440,2014,II,Manis gigantea,Mammalia,Pholidota,Manidae,Manis,CN,UG,NaN,3198.0,3211.0,scales,kg,T,W,-0.4,0.4
934,1998,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,HK,SG,MY,1027.5,1027.0,scales,kg,T,W,0.0,0.0