## Comparative tabulation of Manidae 
### (aggregated and grouped from web download)

In [1]:
import numpy as np
import pandas as pd

In [5]:
df = pd.read_csv('./downloaded/comptab_2019-05-31 12_46_comma_separated.csv')
df.head()

,Year,App.,Taxon,Class,Order,Family,Genus,Importer,Exporter,Origin,Importer reported quantity,Exporter reported quantity,Term,Unit,Purpose,Source
0,1977,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,FR,GB,XX,NaN,4.0,skins,NaN,NaN,NaN
1,1977,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,US,ES,XX,215.0,NaN,shoes,NaN,NaN,NaN
2,1977,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,US,FR,ID,NaN,444.0,skins,NaN,NaN,NaN
3,1977,II,Manis pentadactyla,Mammalia,Pholidota,Manidae,Manis,AU,CN,NaN,2.0,NaN,live,NaN,NaN,NaN
4,1978,II,Manis crassicaudata,Mammalia,Pholidota,Manidae,Manis,US,JP,XX,298.0,NaN,skins,NaN,NaN,NaN

#### quantiy match between importer's and exporter's reports

In [12]:
df_quantity_comparable = df[df['Importer reported quantity'].notnull() & df['Exporter reported quantity'].notnull()]
df_quantity_comparable_match = df_quantity_comparable[df_quantity_comparable['Importer reported quantity'] == df_quantity_comparable['Exporter reported quantity']]
df_quantity_comparable_match.head()

,Year,App.,Taxon,Class,Order,Family,Genus,Importer,Exporter,Origin,Importer reported quantity,Exporter reported quantity,Term,Unit,Purpose,Source
166,1982,II,Manis pentadactyla,Mammalia,Pholidota,Manidae,Manis,JP,US,ID,2.0,2.0,shoes,NaN,T,NaN
349,1984,II,Manis pentadactyla,Mammalia,Pholidota,Manidae,Manis,US,JP,TH,992.0,992.0,skins,NaN,T,NaN
465,1986,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,US,JP,PH,777.0,777.0,skins,NaN,T,NaN
488,1986,II,Manis pentadactyla,Mammalia,Pholidota,Manidae,Manis,JP,US,XX,2.0,2.0,leather items,NaN,T,NaN
505,1987,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,CH,IT,TH,26.0,26.0,shoes,NaN,NaN,NaN

#### quantity conflict between importer's and exporter's reports

In [13]:
df_quantity_comparable_conflict = df_quantity_comparable[df_quantity_comparable['Importer reported quantity'] != df_quantity_comparable['Exporter reported quantity']]
df_quantity_comparable_conflict

,Year,App.,Taxon,Class,Order,Family,Genus,Importer,Exporter,Origin,Importer reported quantity,Exporter reported quantity,Term,Unit,Purpose,Source
68,1981,II,Manis crassicaudata,Mammalia,Pholidota,Manidae,Manis,US,JP,NaN,556.0,884.0,skins,NaN,T,NaN
86,1981,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,US,JP,NaN,1623.0,8325.0,skins,NaN,T,NaN
108,1981,II,Manis pentadactyla,Mammalia,Pholidota,Manidae,Manis,US,JP,NaN,663.0,8367.0,skins,NaN,T,NaN
151,1982,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,US,JP,XX,163.0,7408.0,skins,NaN,T,NaN
222,1983,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,US,IT,SG,15.0,17.0,shoes,NaN,T,NaN
223,1983,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,US,IT,TH,27.0,28.0,shoes,NaN,T,NaN
236,1983,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,US,JP,XX,1440.0,3569.0,skins,NaN,T,NaN
312,1984,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,US,JP,TH,757.0,865.0,skins,NaN,T,NaN
314,1984,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,US,JP,XX,2.0,75.0,leather products (small),NaN,T,NaN
315,1984,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,US,JP,XX,756.0,4632.0,skins,NaN,T,NaN
346,1984,II,Manis pentadactyla,Mammalia,Pholidota,Manidae,Manis,US,JP,ID,5.0,14.0,shoes,NaN,T,NaN
347,1984,II,Manis pentadactyla,Mammalia,Pholidota,Manidae,Manis,US,JP,ID,200.0,420.0,skins,NaN,T,NaN
393,1985,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,US,JP,PH,407.0,300.0,skins,NaN,T,NaN
397,1985,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,US,JP,TH,8845.0,7550.0,skins,NaN,T,NaN
398,1985,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,US,JP,TH,648.0,4940.0,skin pieces,NaN,T,NaN
420,1985,II,Manis pentadactyla,Mammalia,Pholidota,Manidae,Manis,US,JP,TH,400.0,1002.0,skins,NaN,T,NaN
435,1986,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,CH,IT,TH,6.0,14.0,shoes,NaN,NaN,NaN
466,1986,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,US,JP,TH,8950.0,10477.0,skins,NaN,T,NaN
487,1986,II,Manis pentadactyla,Mammalia,Pholidota,Manidae,Manis,JP,US,ID,4.0,2.0,shoes,NaN,T,NaN
493,1986,II,Manis pentadactyla,Mammalia,Pholidota,Manidae,Manis,US,JP,TH,720.0,300.0,skins,NaN,T,NaN
513,1987,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,JP,SG,XX,2300.0,850.0,skins,NaN,T,NaN
530,1987,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,US,JP,TH,3626.0,3166.0,skins,NaN,T,NaN
544,1987,II,Manis pentadactyla,Mammalia,Pholidota,Manidae,Manis,US,CN,NaN,2.0,4.0,live,NaN,Z,NaN
557,1988,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,JP,HK,TH,14.0,5.0,skins,NaN,T,NaN
560,1988,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,JP,SG,LA,4600.0,1000.0,skins,NaN,T,NaN
586,1989,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,CA,US,TH,1.0,3.0,shoes,NaN,T,NaN
780,1994,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,MX,US,LA,1100.0,602.0,skins,NaN,T,W
810,1995,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,MX,US,LA,225.0,215.0,skins,NaN,T,W
812,1995,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,MX,US,LA,35.0,63.0,skin pieces,kg,T,W
858,1996,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,MX,US,LA,999.0,240.0,skins,NaN,T,W
860,1996,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,SG,MY,NaN,5500.0,9430.0,scales,kg,T,W
877,1996,II,Manis tricuspis,Mammalia,Pholidota,Manidae,Manis,US,TG,NaN,1.0,10.0,live,NaN,T,W
890,1997,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,MX,US,LA,2600.0,2100.0,skins,NaN,T,W
934,1998,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,HK,SG,MY,1027.5,1027.0,scales,kg,T,W
981,1999,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,JP,SG,MY,5632.0,5537.0,skins,NaN,T,W
987,1999,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,MX,SG,MY,1700.0,1919.0,skins,NaN,T,W
989,1999,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,SG,MY,NaN,15405.0,12685.0,skins,NaN,T,W
1029,2000,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,MX,JP,MY,2100.0,2260.0,skins,NaN,T,W
1032,2000,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,MX,SG,MY,9987.0,10987.0,skins,NaN,T,W
1033,2000,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,SG,JP,MY,3419.0,3459.0,skins,NaN,T,W
1034,2000,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,SG,MY,NaN,21520.0,5610.0,skins,NaN,T,W
1035,2000,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,US,JP,MY,4136.0,4322.0,skins,NaN,T,W
1042,2000,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,US,MX,LA,925.0,1707.0,leather products (small),NaN,T,W
1052,2000,II,Manis pentadactyla,Mammalia,Pholidota,Manidae,Manis,SG,VN,NaN,153.0,500.0,skins,NaN,T,W
1077,2001,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,MX,JP,MY,750.0,2500.0,skins,NaN,T,W
1099,2002,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,CN,JP,MY,3.0,16.0,leather products (small),NaN,T,W
1101,2002,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,MX,JP,MY,3542.0,2542.0,skins,NaN,T,W
1113,2003,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,MX,JP,MY,1540.0,1500.0,skins,NaN,T,W
1185,2007,II,Manis javanica,Mammalia,Pholidota,Manidae,Manis,US,VN,NaN,750.0,1150.0,specimens,ml,S,W
1226,2008,II,Manis tricuspis,Mammalia,Pholidota,Manidae,Manis,IT,TG,NaN,500.0,5.0,live,NaN,T,R
1369,2012,II,Manis temminckii,Mammalia,Pholidota,Manidae,Manis,US,ZA,NaN,8.0,1.0,specimens,NaN,S,W
1411,2013,II,Manis tricuspis,Mammalia,Pholidota,Manidae,Manis,HK,TG,NaN,60.0,30.0,scales,kg,T,W
1440,2014,II,Manis gigantea,Mammalia,Pholidota,Manidae,Manis,CN,UG,NaN,3198.0,3211.0,scales,kg,T,W
1446,2014,II,Manis gigantea,Mammalia,Pholidota,Manidae,Manis,US,MX,TG,66.0,70.0,leather products (small),NaN,T,W
1536,2015,II,Manis tricuspis,Mammalia,Pholidota,Manidae,Manis,US,TG,NaN,17.0,22.0,live,NaN,T,W
1544,2016,II,Manis spp.,Mammalia,Pholidota,Manidae,Manis,SN,US,XX,2.0,1.0,skin pieces,NaN,L,I
1552,2016,II,Manis gigantea,Mammalia,Pholidota,Manidae,Manis,CN,UG,NaN,4000.0,1000.0,scales,kg,T,W